spring:
  crawler:
    url: https://www.the-blockchain.com/?s=blockchain
    url2: https://www.the-blockchain.com/?s=blockchain
    url3: https://www.newsbtc.com/?s=blockchain
    element-classname: entry-body
    element-classname1: entry-title
    source-path: /home/hoangdd/Downloads
    file-name: /home/hoangdd/Downloads/test
    element-classname2:  entry-meta
